### ISSUE TITLE
Plans to add license and package metadata?

### ISSUE THREAD

**Issue by ericf** [webcomponents/URL#10]
I'm curious if there's plans to make this a standalone npm/Bower package with a `package.json` (and `bower.json`) and license file like: https://github.com/arv/DOM-URL-Polyfill

I ask because @arv's repo says to use this version and the old repo has this project metadata.

**Comment by tomalec** [comment]
+1, any news on that?

**Comment by arv** [comment]
We should do it. Patches welcome.

License should probably be https://github.com/Polymer/polymer/blob/master/LICENSE.txt but it is not clear since https://github.com/annevk/url is missing a license.

@annevk

**Comment by arv** [comment]
Sorry, URL is public domain so that license wold not be correct.

**Comment by tomalec** [comment]
I have just filled a PR with bower.json.
npm may be a little bit more problematic, as it's more restrictive to the
 - license - it need to be in [SPDX](https://spdx.org/licenses/ format or given as LICENSE file,
 - name - lower case, unique, etc.
 - versions - it needs to have one, so will probably require bump per every Polymer version update - many tags for single commit in stable library looked cool.

It would be also nice to use other name for bower package, as there is already registered package called [url](http://bower.io/search/?q=url).

**Comment by annevk** [comment]
Yeah, the original code is under CC0. Not sure if importing into Polymer changed that. Note that these days there's also https://github.com/jsdom/whatwg-url

**Comment by notwaldorf** [comment]
I think @josh added the info to the `package.json` in his GitHub fork, and I'm bullying him to send a PR here

**Comment by TimvdLippe** [comment]
The licenses are now added to bower and package.json.
