### ISSUE TITLE
Make webcomponents the network root

### ISSUE THREAD

**Issue by josh** [webcomponents/URL#20]
So it looks like @annevk declared his repository dead in f56b8a58e3cf7ad2ec4cc1aa44d435d2f51e03ec.

With sign-off from @annevk, @notwaldorf and the powers vested in me as a @github employee, I can turn [webcomponents/URL](https://github.com/webcomponents/URL) into the "network root" so it says @annevk's repo is now a fork of @webcomponents. 

What do you think?

**Comment by notwaldorf** [comment]
I'd add @azakus on this signoff list. I'm just a `webcomponents` janitor. 🗑

**Comment by annevk** [comment]
Sounds fine, though it seems this repository is also out-of-date with the standard. https://github.com/jsdom/whatwg-url is still actively maintained.
