### ISSUE TITLE
Add import file to the repository

### ISSUE THREAD

**Issue by jarrodek** [webcomponents/URL#24]
This repository should have a main html import file that includes the script. This way it can be included in different web components only once.

Let's say I have few web components that uses this repo as a dependency. If I add a `<script>` tag to each of the components the library will be loaded as many times. However using one `import` file it will be downloaded only once. Also build scripts will add the library only once to the bundle.

I know the import is still discussed and not implemented in few browsers but it still would help.

Example import file: `url.html`
```html
<!--
@license
...
-->
<script src="../url/url.js"></script>
```

**Comment by TimvdLippe** [comment]
This package should be imported once per application and is not intended to be loaded multiple times.
