### ISSUE TITLE
Can't install fauxton because of this dependency

### ISSUE THREAD

**Issue by tobiasscheel-dev** [webcomponents/URL#30]
I have a project where I'm using this package: https://www.npmjs.com/package/fauxton
When checking it out fresh after not touching a working copy for a few weeks the npm install exits with this error message.

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @webcomponents/url@0.7.1 build: gulp
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @webcomponents/url@0.7.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

I tried running in a new folder after clearing my npm cache (which would be the way to reproduce this, I guess):

`npm install fauxton`

No success. Same error message. It seems there is something wrong with the gulp dependency in this package. Could you please check if you can reproduce this and get back to me as soon as you can.

**Comment by Wildfirefox** [comment]
+1

**Comment by TimvdLippe** [comment]
This should be fixed in https://github.com/apache/couchdb-fauxton/pull/1092 I have successfully ran `npm install fauxton` on my machine.
